source 'http://rubygems.org'

gem 'jekyll'

group :jekyll-plugins do
  gem 'jekyll-gist'
  gem 'kramdown'
  gem 'jekyll-paginate'
  gem 'rouge'
  gem 'jekyll-watch'
  gem 'algoliasearch-jekyll', '~>0.4.3'
end
